name: music
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  flutter_smart_dialog: ^4.5.5+6
  lottie: ^1.4.3
  connectivity: ^3.0.6
  shared_preferences: ^2.0.13
  flutter_sticky_header: ^0.6.1
  audioplayers: ^0.20.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_swiper_null_safety: ^1.0.2
  loading_indicator: ^3.1.0
  video_player: ^2.4.7
  flutter_screenutil: ^5.5.4
  permission_handler: ^10.2.0
  image_gallery_saver: ^1.7.1
  percent_indicator: ^4.0.1
  sliver_tools: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/videos/
     - assets/lottie/
  fonts:
    - family: GuFengLiShu
      fonts:
        - asset: assets/fonts/GuFengLiShu-2.ttf
    - family: LiShuBold
      fonts:
        - asset: assets\fonts\LiShub.ttf
    - family: PuHuiTi
      fonts:
        - asset: assets\fonts\Puhuiti.ttf
    - family: PuHuiTiX
      fonts:
        - asset: assets\fonts\Puhuitix.ttf
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
